// Mocks generated by Mockito 5.4.2 from annotations
// in poke/test/models/watering_plants/editable_plant_image_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i9;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poke/models/action.dart' as _i7;
import 'package:poke/models/watering_plants/plant.dart' as _i2;
import 'package:poke/persistence/persistence.dart' as _i4;
import 'package:poke/persistence/persistence_event.dart' as _i8;
import 'package:poke/persistence/serializable_event_data.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Plant].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlant extends _i1.Mock implements _i2.Plant {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  set imageUri(Uri? u) => super.noSuchMethod(
        Invocation.setter(
          #imageUri,
          u,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set image(_i3.ImageProvider<Object>? i) => super.noSuchMethod(
        Invocation.setter(
          #image,
          i,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [Persistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistence extends _i1.Mock implements _i4.Persistence {
  @override
  _i5.Future<void> logAction<TEventData extends _i6.SerializableEventData?>(
    _i7.Action<TEventData>? action,
    DateTime? when, {
    TEventData? eventData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAction,
          [
            action,
            when,
          ],
          {#eventData: eventData},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.Action<_i6.SerializableEventData?>?> getAction(
          String? equalityKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAction,
          [equalityKey],
        ),
        returnValue:
            _i5.Future<_i7.Action<_i6.SerializableEventData?>?>.value(),
        returnValueForMissingStub:
            _i5.Future<_i7.Action<_i6.SerializableEventData?>?>.value(),
      ) as _i5.Future<_i7.Action<_i6.SerializableEventData?>?>);

  @override
  _i5.Future<Iterable<_i7.Action<_i6.SerializableEventData?>>>
      getAllActions() => (super.noSuchMethod(
            Invocation.method(
              #getAllActions,
              [],
            ),
            returnValue: _i5
                .Future<Iterable<_i7.Action<_i6.SerializableEventData?>>>.value(
                <_i7.Action<_i6.SerializableEventData?>>[]),
            returnValueForMissingStub: _i5
                .Future<Iterable<_i7.Action<_i6.SerializableEventData?>>>.value(
                <_i7.Action<_i6.SerializableEventData?>>[]),
          ) as _i5.Future<Iterable<_i7.Action<_i6.SerializableEventData?>>>);

  @override
  _i5.Future<void> createAction(
          _i7.Action<_i6.SerializableEventData?>? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAction,
          [action],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAction(
    String? equalityKey,
    _i7.Action<_i6.SerializableEventData?>? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAction,
          [
            equalityKey,
            action,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteEvent(
    _i7.Action<_i6.SerializableEventData?>? a,
    DateTime? eventDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [
            a,
            eventDate,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i8.PersistenceEvent> getNotificationStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStream,
          [],
        ),
        returnValue: _i5.Stream<_i8.PersistenceEvent>.empty(),
        returnValueForMissingStub: _i5.Stream<_i8.PersistenceEvent>.empty(),
      ) as _i5.Stream<_i8.PersistenceEvent>);

  @override
  _i5.Future<Uri> uploadData(
    _i9.Uint8List? bytes,
    String? storageKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadData,
          [
            bytes,
            storageKey,
          ],
        ),
        returnValue: _i5.Future<Uri>.value(_FakeUri_0(
          this,
          Invocation.method(
            #uploadData,
            [
              bytes,
              storageKey,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<Uri>.value(_FakeUri_0(
          this,
          Invocation.method(
            #uploadData,
            [
              bytes,
              storageKey,
            ],
          ),
        )),
      ) as _i5.Future<Uri>);

  @override
  _i5.Future<_i9.Uint8List?> getUploadedData(String? storageKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadedData,
          [storageKey],
        ),
        returnValue: _i5.Future<_i9.Uint8List?>.value(),
        returnValueForMissingStub: _i5.Future<_i9.Uint8List?>.value(),
      ) as _i5.Future<_i9.Uint8List?>);
}
