// Mocks generated by Mockito 5.4.2 from annotations
// in poke/test/models/watering_plants/new_instance_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke/models/action.dart' as _i6;
import 'package:poke/persistence/action_with_events.dart' as _i7;
import 'package:poke/persistence/persistence.dart' as _i3;
import 'package:poke/persistence/persistence_event.dart' as _i8;
import 'package:poke/persistence/serializable_event_data.dart' as _i5;
import 'package:uuid/data.dart' as _i11;
import 'package:uuid/uuid.dart' as _i10;
import 'package:uuid/uuid_value.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuidValue_1 extends _i1.SmartFake implements _i2.UuidValue {
  _FakeUuidValue_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Persistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistence extends _i1.Mock implements _i3.Persistence {
  @override
  _i4.Future<void> logAction<TEventData extends _i5.SerializableEventData?,
          TAction extends _i6.Action<TEventData>>(
    TAction? action,
    DateTime? when, {
    TEventData? eventData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAction,
          [
            action,
            when,
          ],
          {#eventData: eventData},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<
          _i7.ActionWithEvents<_i5.SerializableEventData?,
              _i6.Action<_i5.SerializableEventData?>>?>
      getAction(String? equalityKey) => (super.noSuchMethod(
            Invocation.method(
              #getAction,
              [equalityKey],
            ),
            returnValue: _i4.Future<
                _i7.ActionWithEvents<_i5.SerializableEventData?,
                    _i6.Action<_i5.SerializableEventData?>>?>.value(),
            returnValueForMissingStub: _i4.Future<
                _i7.ActionWithEvents<_i5.SerializableEventData?,
                    _i6.Action<_i5.SerializableEventData?>>?>.value(),
          ) as _i4.Future<
              _i7.ActionWithEvents<_i5.SerializableEventData?,
                  _i6.Action<_i5.SerializableEventData?>>?>);

  @override
  _i4.Future<
      Iterable<
          _i7.ActionWithEvents<_i5.SerializableEventData?,
              _i6.Action<_i5.SerializableEventData?>>>> getAllEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<
            Iterable<
                _i7.ActionWithEvents<_i5.SerializableEventData?,
                    _i6.Action<_i5.SerializableEventData?>>>>.value(<_i7
            .ActionWithEvents<_i5.SerializableEventData?,
                _i6.Action<_i5.SerializableEventData?>>>[]),
        returnValueForMissingStub: _i4.Future<
            Iterable<
                _i7.ActionWithEvents<_i5.SerializableEventData?,
                    _i6.Action<_i5.SerializableEventData?>>>>.value(<_i7
            .ActionWithEvents<_i5.SerializableEventData?,
                _i6.Action<_i5.SerializableEventData?>>>[]),
      ) as _i4.Future<
          Iterable<
              _i7.ActionWithEvents<_i5.SerializableEventData?,
                  _i6.Action<_i5.SerializableEventData?>>>>);

  @override
  _i4.Future<void> createAction(
          _i6.Action<_i5.SerializableEventData?>? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAction,
          [action],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateAction(
    String? equalityKey,
    _i6.Action<_i5.SerializableEventData?>? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAction,
          [
            equalityKey,
            action,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteEvent(
    _i6.Action<_i5.SerializableEventData?>? a,
    DateTime? eventDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [
            a,
            eventDate,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i8.PersistenceEvent> getNotificationStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStream,
          [],
        ),
        returnValue: _i4.Stream<_i8.PersistenceEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i8.PersistenceEvent>.empty(),
      ) as _i4.Stream<_i8.PersistenceEvent>);

  @override
  _i4.Future<Uri> uploadData(
    _i9.Uint8List? bytes,
    String? storageKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadData,
          [
            bytes,
            storageKey,
          ],
        ),
        returnValue: _i4.Future<Uri>.value(_FakeUri_0(
          this,
          Invocation.method(
            #uploadData,
            [
              bytes,
              storageKey,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<Uri>.value(_FakeUri_0(
          this,
          Invocation.method(
            #uploadData,
            [
              bytes,
              storageKey,
            ],
          ),
        )),
      ) as _i4.Future<Uri>);

  @override
  _i4.Future<_i9.Uint8List?> getUploadedData(String? storageKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadedData,
          [storageKey],
        ),
        returnValue: _i4.Future<_i9.Uint8List?>.value(),
        returnValueForMissingStub: _i4.Future<_i9.Uint8List?>.value(),
      ) as _i4.Future<_i9.Uint8List?>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i10.Uuid {
  @override
  String v1({
    Map<String, dynamic>? options,
    _i11.V1Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  List<int> v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i11.V1Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1buffer,
          [buffer],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v1obj({
    Map<String, dynamic>? options,
    _i11.V1Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1obj,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v1obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
        returnValueForMissingStub: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v1obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v4({
    Map<String, dynamic>? options,
    _i11.V4Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  List<int> v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i11.V4Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4buffer,
          [buffer],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v4obj({
    Map<String, dynamic>? options,
    _i11.V4Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4obj,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v4obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
        returnValueForMissingStub: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v4obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i11.V5Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5,
          [
            namespace,
            name,
          ],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  List<int> v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i11.V5Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5buffer,
          [
            namespace,
            name,
            buffer,
          ],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v5obj(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i11.V5Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5obj,
          [
            namespace,
            name,
          ],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v5obj,
            [
              namespace,
              name,
            ],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
        returnValueForMissingStub: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v5obj,
            [
              namespace,
              name,
            ],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v6({_i11.V6Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v6,
          [],
          {#config: config},
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  List<int> v6buffer(
    List<int>? buffer, {
    _i11.V6Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v6buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v6obj({_i11.V6Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v6obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v6obj,
            [],
            {#config: config},
          ),
        ),
        returnValueForMissingStub: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v6obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v7({_i11.V7Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v7,
          [],
          {#config: config},
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  List<int> v7buffer(
    List<int>? buffer, {
    _i11.V7Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v7buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v7obj({_i11.V7Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v7obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v7obj,
            [],
            {#config: config},
          ),
        ),
        returnValueForMissingStub: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v7obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v8({_i11.V8Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8,
          [],
          {#config: config},
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);

  @override
  List<int> v8buffer(
    List<int>? buffer, {
    _i11.V8Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v8buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
        returnValueForMissingStub: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v8obj({_i11.V8Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v8obj,
            [],
            {#config: config},
          ),
        ),
        returnValueForMissingStub: _FakeUuidValue_1(
          this,
          Invocation.method(
            #v8obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);
}
