// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPbaRBxG02a0QjZkamfiVH6vxdQzJ6Pzs',
    appId: '1:201274280583:web:f1f8ff038391890c95c622',
    messagingSenderId: '201274280583',
    projectId: 'plant-reminder-90745',
    authDomain: 'plant-reminder-90745.firebaseapp.com',
    storageBucket: 'plant-reminder-90745.appspot.com',
    measurementId: 'G-1X2E1ZC9VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiTrb9EFwZPxsem-HRPfz-LI_bjl0mYDw',
    appId: '1:201274280583:android:4e1807ba30673f5095c622',
    messagingSenderId: '201274280583',
    projectId: 'plant-reminder-90745',
    storageBucket: 'plant-reminder-90745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFl4_MTtdHpzApSurZfmwJmyMNpa7WbSA',
    appId: '1:201274280583:ios:7fb26b737efd114995c622',
    messagingSenderId: '201274280583',
    projectId: 'plant-reminder-90745',
    storageBucket: 'plant-reminder-90745.appspot.com',
    androidClientId: '201274280583-t4m3q567i1m9jsdkrh3kvjqogfpgn9ah.apps.googleusercontent.com',
    iosClientId: '201274280583-eih81te6e0ibj1g5ort2fbtemn600esj.apps.googleusercontent.com',
    iosBundleId: 'com.example.poke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFl4_MTtdHpzApSurZfmwJmyMNpa7WbSA',
    appId: '1:201274280583:ios:80ab72f1af4b567595c622',
    messagingSenderId: '201274280583',
    projectId: 'plant-reminder-90745',
    storageBucket: 'plant-reminder-90745.appspot.com',
    androidClientId: '201274280583-t4m3q567i1m9jsdkrh3kvjqogfpgn9ah.apps.googleusercontent.com',
    iosClientId: '201274280583-omsslj48liinsdaqviebjilcasp670qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.poke.RunnerTests',
  );
}
