// Mocks generated by Mockito 5.4.2 from annotations
// in poke/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke/models/action.dart' as _i5;
import 'package:poke/persistence/persistence.dart' as _i2;
import 'package:poke/persistence/persistence_event.dart' as _i6;
import 'package:poke/persistence/serializable_event_data.dart' as _i4;
import 'package:poke/predictor/predictor.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Persistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistence extends _i1.Mock implements _i2.Persistence {
  @override
  _i3.Future<void> logAction<TEventData extends _i4.SerializableEventData?>(
    _i5.Action<TEventData>? action,
    DateTime? when, {
    TEventData? eventData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAction,
          [
            action,
            when,
          ],
          {#eventData: eventData},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.Action<_i4.SerializableEventData?>?> getAction(
          String? equalityKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAction,
          [equalityKey],
        ),
        returnValue:
            _i3.Future<_i5.Action<_i4.SerializableEventData?>?>.value(),
        returnValueForMissingStub:
            _i3.Future<_i5.Action<_i4.SerializableEventData?>?>.value(),
      ) as _i3.Future<_i5.Action<_i4.SerializableEventData?>?>);

  @override
  _i3.Future<Iterable<_i5.Action<_i4.SerializableEventData?>>>
      getAllActions() => (super.noSuchMethod(
            Invocation.method(
              #getAllActions,
              [],
            ),
            returnValue: _i3
                .Future<Iterable<_i5.Action<_i4.SerializableEventData?>>>.value(
                <_i5.Action<_i4.SerializableEventData?>>[]),
            returnValueForMissingStub: _i3
                .Future<Iterable<_i5.Action<_i4.SerializableEventData?>>>.value(
                <_i5.Action<_i4.SerializableEventData?>>[]),
          ) as _i3.Future<Iterable<_i5.Action<_i4.SerializableEventData?>>>);

  @override
  _i3.Future<void> createAction(
          _i5.Action<_i4.SerializableEventData?>? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAction,
          [action],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateAction(
    String? equalityKey,
    _i5.Action<_i4.SerializableEventData?>? action,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAction,
          [
            equalityKey,
            action,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEvent(
    _i5.Action<_i4.SerializableEventData?>? a,
    DateTime? eventDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [
            a,
            eventDate,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i6.PersistenceEvent> getNotificationStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationStream,
          [],
        ),
        returnValue: _i3.Stream<_i6.PersistenceEvent>.empty(),
        returnValueForMissingStub: _i3.Stream<_i6.PersistenceEvent>.empty(),
      ) as _i3.Stream<_i6.PersistenceEvent>);

  @override
  _i3.Future<Uri> uploadData(
    _i7.Uint8List? bytes,
    String? storageKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadData,
          [
            bytes,
            storageKey,
          ],
        ),
        returnValue: _i3.Future<Uri>.value(_FakeUri_0(
          this,
          Invocation.method(
            #uploadData,
            [
              bytes,
              storageKey,
            ],
          ),
        )),
        returnValueForMissingStub: _i3.Future<Uri>.value(_FakeUri_0(
          this,
          Invocation.method(
            #uploadData,
            [
              bytes,
              storageKey,
            ],
          ),
        )),
      ) as _i3.Future<Uri>);

  @override
  _i3.Future<_i7.Uint8List?> getUploadedData(String? storageKey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUploadedData,
          [storageKey],
        ),
        returnValue: _i3.Future<_i7.Uint8List?>.value(),
        returnValueForMissingStub: _i3.Future<_i7.Uint8List?>.value(),
      ) as _i3.Future<_i7.Uint8List?>);
}

/// A class which mocks [Predictor].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictor extends _i1.Mock implements _i8.Predictor {
  @override
  DateTime? predictNext(_i5.Action<_i4.SerializableEventData?>? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictNext,
          [action],
        ),
        returnValueForMissingStub: null,
      ) as DateTime?);
}
