// Mocks generated by Mockito 5.4.2 from annotations
// in poke/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke/models/action.dart' as _i5;
import 'package:poke/persistence/action_with_events.dart' as _i6;
import 'package:poke/persistence/persistence.dart' as _i2;
import 'package:poke/persistence/serializable_event_data.dart' as _i4;
import 'package:poke/predictor/predictor.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Persistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistence extends _i1.Mock implements _i2.Persistence {
  @override
  _i3.Future<void> logAction<TEventData extends _i4.SerializableEventData?,
          TAction extends _i5.Action<TEventData>>(
    TAction? action,
    DateTime? when, {
    TEventData? eventData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAction,
          [
            action,
            when,
          ],
          {#eventData: eventData},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<
      Iterable<
          _i6.ActionWithEvents<_i4.SerializableEventData?,
              _i5.Action<_i4.SerializableEventData?>>>> getAllEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i3.Future<
            Iterable<
                _i6.ActionWithEvents<_i4.SerializableEventData?,
                    _i5.Action<_i4.SerializableEventData?>>>>.value(<_i6
            .ActionWithEvents<_i4.SerializableEventData?,
                _i5.Action<_i4.SerializableEventData?>>>[]),
        returnValueForMissingStub: _i3.Future<
            Iterable<
                _i6.ActionWithEvents<_i4.SerializableEventData?,
                    _i5.Action<_i4.SerializableEventData?>>>>.value(<_i6
            .ActionWithEvents<_i4.SerializableEventData?,
                _i5.Action<_i4.SerializableEventData?>>>[]),
      ) as _i3.Future<
          Iterable<
              _i6.ActionWithEvents<_i4.SerializableEventData?,
                  _i5.Action<_i4.SerializableEventData?>>>>);

  @override
  _i3.Future<void> createAction(
          _i5.Action<_i4.SerializableEventData?>? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAction,
          [action],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteEvent(
    _i5.Action<_i4.SerializableEventData?>? a,
    DateTime? eventDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [
            a,
            eventDate,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [Predictor].
///
/// See the documentation for Mockito's code generation for more information.
class MockPredictor extends _i1.Mock implements _i7.Predictor {
  @override
  DateTime? predictNext(
          _i6.ActionWithEvents<_i4.SerializableEventData?,
                  _i5.Action<_i4.SerializableEventData?>>?
              actionWithEvents) =>
      (super.noSuchMethod(
        Invocation.method(
          #predictNext,
          [actionWithEvents],
        ),
        returnValueForMissingStub: null,
      ) as DateTime?);
}
